repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v2.3.0
        hooks:
        -   id: check-yaml
        -   id: check-merge-conflict
        -   id: end-of-file-fixer
        -   id: requirements-txt-fixer
    -   repo: https://github.com/psf/black
        rev: stable
        hooks:
        -   id: black
    -   repo: https://github.com/asottile/reorder_python_imports
        rev: v1.3.5
        hooks:
        -   id: reorder-python-imports
            language_version: python3
    -   repo: https://gitlab.com/pycqa/flake8
        rev: 3.8.1
        hooks:
        -   id: flake8
            language_version: python3
